#!/bin/bash

# check if user input supplied
if [ -z "$1" ]
  then
    echo "No input supplied"
else

PHRASE=$*

TRANSLATION="$(echo $PHRASE | trans -e google -s tl -t en -show-original n -show-original-phonetics n -show-translation y -no-ansi -show-translation-phonetics n -show-prompt-message n -show-languages n -show-original-dictionary n -show-dictionary n -show-alternatives n)"

echo "$TRANSLATION"
fi
